### ISSUE TITLE
Lambdas & JDK 8 support

### ISSUE THREAD

**Issue by teras** [ReadyTalk/hello-ios#10]
II am not sure if I should report this here, or on the main Avian project, but it seems like it is a problem found in hello-ios; the avian test succeds with no problem.

I was trying to check whether lambdas are supported.
Thus I appended the minimum source code:
  ```
Runnable q = () -> System.out.println("It works!");
q.run();
```
and of course I took care to update the java version compilation flag from 1.7 to 1.8.
(is there a reason for this? Or is just forgotten?)

Then I started the make command as usual, and I got this error message:
```
...

mkdir -p build/stage2
cp -r build/stage1/* build/stage2
../avian/build/ios-x86_64-bootimage/bootimage-generator -cp build/stage2 -bootimage build/bootimage-bin.o \
		-codeimage build/codeimage-bin.o 
make: *** [build/bootimage-bin.o] Abort trap: 6
make: *** Deleting file `build/bootimage-bin.o'
```

Ι tried a similar test with "pure" avian, adding the same code and following the "Embedding" test, in order to mimic as close as possible the procedure. This test wa sucessful.

Is a specific reason JDK8 is not working with ios, or is a missing configuration somewhere?

**Comment by dicej** [comment]
Thanks for reporting this (and thanks also for the earlier patches).

This should definitely work, so I don't know offhand what's wrong.  I won't have time this weekend to investigate it much, but I'll do so on Monday or Tuesday when I have a chance.

**Comment by dicej** [comment]
This should fix it: https://github.com/ReadyTalk/hello-ios/commit/a927e0ff7dde5b95d76637b890a58872a6b7636e

**Comment by teras** [comment]
I thought I tried to do the same, but I didn't manage to make it work; probably I wasn't able to configure it correctly. 
I can't test it these days since now I am abroad but I'm sure it will work.
Thank you for the support

**Comment by teras** [comment]
As a second thought, probably avian should be updated to display a relevant error instead of crashing under this configuration ( with missing hosvm parameter ) ?

**Comment by dicej** [comment]
Agreed.  I'll push a PR for that when I have a chance.

**Comment by dicej** [comment]
This PR provides an error message: https://github.com/ReadyTalk/avian/pull/499
