### ISSUE TITLE
EXC_BAD_ACCESS instead of NullPointerException

### ISSUE THREAD

**Issue by teras** [ReadyTalk/hello-ios#12]
I have found that if a null pointer is found, the system instead of throwing a NullPointerException, an EXC_BAD_ACCESS is found instead. It is easily reproducible if we write something like

```
Object a = null;
a.toString();
```

The expected behaviour would be to throw a null pointer exception instead. The problem is a serious one, not only because no exception is thrown, but more importantly that a try-catch block will will not actually catch it, but will crash the application.

This is happening at line 8510 of file "compile.cpp" in the command that reads

```
result = vmInvoke(
        t,
        reinterpret_cast<void*>(methodAddress(t, method)),
        arguments->array,
        arguments->position * BytesPerWord,
        t->arch->alignFrameSize(t->arch->argumentFootprint(arguments->position))
        * BytesPerWord,
        returnType);
  }
```

Xcode is helpful to tell me more info about the current thread status:

```
thread  vm::Thread *    NULL    
method  vm::GcMethod *  NULL    
arguments   (anonymous namespace)::local::ArgumentList *    NULL    
stackLimit  uintptr_t   
resource_8496   Resource_8496   
returnType  unsigned int    0
t   (anonymous namespace)::local::MyThread *    0x7fe10c825600  0x00007fe10c825600
result  uint64_t    
r   vm::object  0x0 
stackPosition   uintptr_t   
returnCode  unsigned int    
checkpoint  (anonymous namespace)::local::MyCheckpoint  
trace   (anonymous namespace)::local::MyThread::CallTrace   
exception   vm::GcThrowable *   NULL    
```

It actually goes one level deeper, in ASM code `LvmInvoke_argumentTest` (no debug information there unfortunately).

The target is x86_64, but I also tried arm64, with exactly the same behaviour.

**Comment by joshuawarner32** [comment]
Thanks for the bug report.

However, unless something truly bizarre is happening, what you're seeing is in fact not a bug at all, but just a side-effect of having a debugger attached (xcode/lldb in this case).

Avian implements exceptions by actually letting an access violation happen, then catching that access violation and turning it into a Java-level exception.  Debuggers like to catch that exception before avian is able to, and so you see the EXC_BAD_ACCESS in the debugger.

If you _continue_ in the debugger, the handler avian has installed should be called and the exception should be generated.  Ditto for if you're not running with a debugger attached at all.  I'm not sure if you can tell xcode to not attach a debugger - but you should be able to launch your app directly from the home screen.

If the EXC_BAD_ACCESS is problematic for other reasons, you can build avian with `process=interpret`, where we don't depend on processor-level exceptions to implement java-level exceptions.  Instead, we actually check for null pointers every time we access them.

Please let us know if you're seeing what you expect without a debugger or when continuing in the debugger.

**Comment by teras** [comment]
Indeed you are right, of course. It seems like a debugger issue.

The strange thing is that, I tried (clicking on every logical possible button) to make the debugger continue the code execution, but it stubbornly refused. I also tried writing the `process continue` and `finish` command on the lldb command promt, with no luck. The execution remained there forever.

The only way I found to continue the execution is by detaching the debugger completely and reattaching it again (and loosing the console of course then). So practically it is not possible to persuade lldb to allow the code execution?

Thank you for the support anyway and for the quick response.

**Comment by dicej** [comment]
Yeah, there's something about LLDB, at least when debugging iOS apps, such that you can't continue after a bad access.  It works just fine in GDB on most platforms.  The workaround I've used is run it outside the debugger so I can get an NPE stack trace, fix the NPE, and then run it in the debugger again.
